#!/bin/sh

set -e
. "$(dirname "$0")/.common.sh"

pkg_list="$(dl_file "$packages_url")"

mkdir -v -p "$DESTDIR/opt/postgres"

for pkg_name in $pg_pkgs;do
  pkg_fname="$(grep -e "^Package: $pkg_name\$" -e "^Filename: " "$pkg_list" | grep -A1 ^Package: | awk '/^Filename:/{print $2}')"
  test -n "$pkg_fname" || {
    echo "Could not find package '$pkg_name' from $packages_url" >&2
    exit 1
  }
  deb="$(dl_file "$repo_url/$pkg_fname")"
  dpkg-deb --fsys-tarfile "$deb" | tar xv --wildcards --xform 's@^./usr@opt/postgres@' -C "$DESTDIR" "./usr/*"
done
